version: "2.4"
services:
  reverse_proxy:
    image: prise_de_rdv_reverse_proxy
    container_name: prise_de_rdv_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - prise_de_rdv_network
    depends_on:
      - server
      - ui

  ui:
    image: prise_de_rdv_ui
    container_name: prise_de_rdv_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - prise_de_rdv_network
    depends_on:
      - server

  server:
    image: prise_de_rdv_server
    container_name: prise_de_rdv_server
    build:
      context: server
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - prise_de_rdv_network
    depends_on:
      - mongodb
    environment:
      - PRISE_DE_RDV_MONGODB_URI=mongodb://mongodb:27017/prise-de-rdv?retryWrites=true&w=majority
      - PRISE_DE_RDV_OUTPUT_DIR=/data

  mongodb:
    image: mongo:4.2.6-bionic
    container_name: prise_de_rdv_mongodb
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - prise_de_rdv_network

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: prise_de_rdv_mailhog
    networks:
      - prise_de_rdv_network
    volumes:
      - ./sandbox/auth.txt:/app/auth.txt
    environment:
      - MH_AUTH_FILE=/app/auth.txt

networks:
  prise_de_rdv_network:
    name: prise_de_rdv_network
