// Global style variables
export const background = {
  app: "#e5e5e5",
  white: "#ffffff",
  grey: "#f0f0f0",
  blue: "#206bc4",
  sidebar: "#fafafaff",
  header: "#d9ead3",
  blueLight: "#e8f0f9",
};

export const color = {
  transparent: "transparent",
  white: "white",
  black: "black",
  veryLightGrey: "#f3f3f3ff",
  ultraGrey: "#fafafaff",
  lightGrey: "#efefef",
  otherLightGrey: "#BDBDBD",
  hoverGrey: "#EAECF0",
  lightBlueGrey: "#F5F5F7",
  mediumGrey: "#d9d9d9ff",
  otherMediumGrey: "#cccccc",
  mediumDarkGrey: "#666666",
  darkGrey: "#232E3C",
  grey: "#dee2e6",
  beige: "antiquewhite",
  lightPurple: "#d9d2e9ff",
  lightYellow: "#fff2ccff",
  yellow: "#ffe599ff",
  mediumYellow: "#f1c232",
  ultraLightOrange: "#fff3e0ff",
  lightOrange: "#f9cb9cff",
  mediumOrange: "#f6b26bff",
  orange: "#ff9900ff",
  redPink: "#f4ccccff",
  red: "#cc0000ff",
  coral: "#e9967a",
  blue: "#206BC4",
  lightBlue: "#cfe2f3ff",
  lightGreen: "#d9ead3ff",
  green: "#b6d7a8ff",
  darkGreen: "#38761d",
};

export const typography = {
  type: {
    primary: '"Arial", "sans-serif"',
    code: '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace',
  },
  fontFamily: {
    inter: "Inter",
  },
  fontWeight: {
    lowWeight: "300",
    regular: "400",
    xxbold: "500",
    semibold: "600",
    bold: "700",
    extrabold: "800",
    black: "900",
  },
  fontSize: {
    em0: "0.9em",
    em1: "1em",
    s0: "10px",
    s1: "12px",
    s2: "14px",
    s3: "16px",
    s4: "18px",
    m1: "20px",
    m2: "22px",
    m3: "24px",
    l1: "28px",
    l2: "32px",
    l3: "48px",
    code: "90px",
    icon: "90px",
  },
  style: {
    normal: "normal",
    italic: "italic",
  },
};

export const spacing = {
  padding: {
    xxxsmall: "4px",
    xxsmall: "6px",
    xsmall: "8px",
    small: "10px",
    xxmedium: "16px",
    xmedium: "20px",
    medium: "25px",
    large: "30px",
    xlarge: "44px",
    xxlarge: "50px",
    xxxlarge: "70px",
    centerContainer: "209px",
  },
  borderRadius: {
    small: "5px",
    default: "10px",
  },
};
